modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="a_mod"
version="1.0.0"
displayName="a mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="xjjak, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.a_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.a_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration