modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="a_mod"
version="1.0.5"
displayName="Chicken's Fantastic Idea"
displayURL="https://github.com/xjjakm/Chicken-s-Fantastic-Idea"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="chxjj, MCreator"
description="\u5947\u602A\u4E1C\u897F\u4E00\u5806"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.a_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.123,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.a_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration